# Generated by Django 3.2.9 on 2021-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logIp', models.GenericIPAddressField()),
                ('dt_vl', models.DateField()),
                ('vl_brl', models.DecimalField(decimal_places=3, max_digits=6)),
                ('vl_ien', models.DecimalField(decimal_places=3, max_digits=6)),
                ('vl_eur', models.DecimalField(decimal_places=3, max_digits=6)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
